[book]
authors = ["smdaa"]
language = "en"
multilingual = false
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/smdaa/smdaa.github.io.git"