baseURL = 'https://smdaa.github.io/'
languageCode = 'en-us'
title = "smdaa"
theme = "xmin"
enableRobotsTXT = true

[params]
  description = "A minimalist Hugo site"
  footer = "&copy; 2025 Saad Mdaa"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/post/"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3

[markup.highlight]
style = "github"
